version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:13-browsers
        environment: 
          CHROME_BIN: "/usr/bin/google-chrome"

    working_directory: ~/repo

    steps:
      - run:
            name: "Checking Versions"
            command: |
              node --version
              yarn --version
              
      - checkout


      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # install dependencies
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      # run tests!
      - run: yarn test
